### ISSUE TITLE
Cannot find module './node_modules/cheerio'

### ISSUE THREAD

**Issue by RichardYan314** [RichardYan314/hexo-pandoc-tippy#8]
抱歉失误删除了 @君上 提出的 issue. 我搜不到你的 ID, 麻烦你看到以后回复下。

-----

全新安装 0.4.3 版后出现 `Cannot find module './node_modules/cheerio'`:

```
Error: Cannot find module './node_modules/cheerio'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at module.exports (C:\Users\richard\Documents\programs\temp\node_modules\hexo-pandoc-tippy\fixFootnotes.js:2:19)
    at Hexo.<anonymous> (C:\Users\richard\Documents\programs\temp\node_modules\hexo-pandoc-tippy\index.js:62:5)
    at Hexo.tryCatcher (C:\Users\richard\Documents\programs\temp\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (C:\Users\richard\Documents\programs\temp\node_modules\bluebird\js\release\method.js:15:34)
    at Promise.each.filter (C:\Users\richard\Documents\programs\temp\node_modules\hexo\lib\extend\filter.js:62:52)
    at tryCatcher (C:\Users\richard\Documents\programs\temp\node_modules\bluebird\js\release\util.js:16:23)
    at Object.gotValue (C:\Users\richard\Documents\programs\temp\node_modules\bluebird\js\release\reduce.js:166:18)
    at Object.gotAccum (C:\Users\richard\Documents\programs\temp\node_modules\bluebird\js\release\reduce.js:155:25)
    at Object.tryCatcher (C:\Users\richard\Documents\programs\temp\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\richard\Documents\programs\temp\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\richard\Documents\programs\temp\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Users\richard\Documents\programs\temp\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Users\richard\Documents\programs\temp\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\Users\richard\Documents\programs\temp\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Users\richard\Documents\programs\temp\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\richard\Documents\programs\temp\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\richard\Documents\programs\temp\node_modules\bluebird\js\release\async.js:15:14)
    at runCallback (timers.js:705:18)
```

**Comment by RichardYan314** [comment]
已经在 0.4.4 版本中修复

**Comment by vtkdhhgg** [comment]
好的，麻烦了。

**Comment by RichardYan314** [comment]
你试试，修好了吗



---Original---

**Comment by vtkdhhgg** [comment]
前辈，我重新安装了一遍。没有了这个问题，但是还是会自动创建 `./node_modules/` ,文件。

**Comment by vtkdhhgg** [comment]
不知道是什么问题...

**Comment by RichardYan314** [comment]
没事，node_modules那个是我搞错了。只要不报错说找不到cheerio就算合格了



---Original---

**Comment by vtkdhhgg** [comment]
我在next的主题目录中安装插件（不是在博客根目录），就不会自动创建 `/node_modules/`文件。
但是就无法使用这个插件的功能。
我看一了下，好像是因为没有将js,css文件创建到public目录中。（attachTooltips.js）
是不是只要修改相关的路径就可以在next主题中安装这个插件。
比如：（/hexo-pandoc-tippy/index.js）
```
// generate js script
assets.push({
    path: 'js/attachTooltips.js',
    data: format(
        fs.readFileSync(__dirname+'/attachTooltips.js'),
        JSON.stringify(config)
    )
});
```

**Comment by vtkdhhgg** [comment]
知道了，好的，好的。再次感谢！！！

**Comment by RichardYan314** [comment]
插件一定要在博客根目录安装并且按照说明添加到_config.yaml中



---Original---

**Comment by vtkdhhgg** [comment]
好的，知道了。谢谢您了！

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
