### ISSUE TITLE
panflute Exception: unknown tag: Caption

### ISSUE THREAD

**Issue by Core00077** [RichardYan314/hexo-pandoc-tippy#9]
许久未写blog，再次写好后渲染的时候出现了貌似是panflute的问题，试过推荐的1.10.6和最新的1.12.5版本。不是很清楚Caption是一个什么样的unknown tag。猜测是py3.8导致的问题？希望大佬有空看看。

```python3
Error: 
[ERROR][hexo-renderer-pandoc] On /home/core/Documents/hexo_blogs/source/_posts/2018总结.md
[ERROR][hexo-renderer-pandoc] pandoc exited with code 83: Traceback (most recent call last):
  File "node_modules/hexo-pandoc-tippy/pandocFilter.py", line 49, in <module>
    main()
  File "node_modules/hexo-pandoc-tippy/pandocFilter.py", line 45, in main
    return run_filter(action, prepare=prepare, finalize=finalize, doc=doc) 
  File "/usr/lib/python3.8/site-packages/panflute/io.py", line 266, in run_filter
    return run_filters([action], *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/panflute/io.py", line 239, in run_filters
    doc = load(input_stream=input_stream)
  File "/usr/lib/python3.8/site-packages/panflute/io.py", line 59, in load
    doc = json.load(input_stream, object_pairs_hook=from_json)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 370, in loads
    return cls(**kw).decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
  File "/usr/lib/python3.8/site-packages/panflute/elements.py", line 1532, in from_json
    raise Exception('unknown tag: ' + tag)
Exception: unknown tag: Caption
Error running filter node_modules/hexo-pandoc-tippy/pandocFilter.py:
Filter returned error status 1

    at Hexo.pandocRenderer (/home/core/Documents/hexo_blogs/node_modules/hexo-renderer-pandoc/index.js:114:11)
    at Hexo.tryCatcher (/home/core/Documents/hexo_blogs/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/home/core/Documents/hexo_blogs/node_modules/bluebird/js/release/method.js:15:34)
    at /home/core/Documents/hexo_blogs/node_modules/hexo/lib/hexo/render.js:60:20
    at tryCatcher (/home/core/Documents/hexo_blogs/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/core/Documents/hexo_blogs/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/core/Documents/hexo_blogs/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/home/core/Documents/hexo_blogs/node_modules/bluebird/js/release/promise.js:606:10)
    at _drainQueueStep (/home/core/Documents/hexo_blogs/node_modules/bluebird/js/release/async.js:142:12)
    at _drainQueue (/home/core/Documents/hexo_blogs/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/home/core/Documents/hexo_blogs/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/core/Documents/hexo_blogs/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (internal/timers.js:461:21)
```

**Comment by Core00077** [comment]
使用的pandoc 版本为2.10.1

**Comment by RichardYan314** [comment]
我大概知道问题在哪里。可以给一份能再现问题的 md 文件吗



---Original---

**Comment by Core00077** [comment]
https://raw.githubusercontent.com/Core00077/hexo_blogs/master/source/_posts/2018%E6%80%BB%E7%BB%93.md

**Comment by RichardYan314** [comment]
奇怪了，这边复现不出来。能尝试构造一份 minimal reproducible example 吗？

 

我原以为问题出在使用了 hexo 的 tag. 现在看来暂时还不能确定是这样的。

**Comment by Core00077** [comment]
我理解你的意思，不过我个人认为应该是由于Python升级导致的问题，当前使用的py版本是3.8，而之前一直用的3.6和3.7下渲染似乎没有出现问题。

**Comment by RichardYan314** [comment]
原来还有这样的可能性。python 3.8 版本应该并不直接影响，可能是 panflute 的原因。我解决了手上的工作就来处理这个。

可以给一份 minimal reproducible example 吗？

**Comment by Core00077** [comment]
我也认为是panflute的问题，等我方便了我会给你一份demo看

**Comment by RichardYan314** [comment]
你的 pandoc 版本是什么？我在我的 panflute 下检视语法树并没有发现叫做 caption 的标签。所以现在认为是 pandoc 导致的问题。我这边 pandoc 版本是 2.9.1.1

**Comment by Core00077** [comment]
前面写了的，2.10.1

**Comment by Core00077** [comment]
因为这边使用的manjaro，所以pandoc版本会比较新，刚刚尝试了2.9.1.1版本的pandoc，但降级到2.9.1.1和2.9.2都会由于依赖版本不符合导致降级后的pandoc无法使用，所以也没办法确认是否为pandoc的问题。

另外我尝试了制作一个[minimal demo](https://coreja.com/test.zip)，`npm install`之后即可复现。（如果没复现那就只能是pandoc/panflute/python等上游版本问题了）

**Comment by RichardYan314** [comment]
使用 pandoc 2.9.11 无法复现，升级 2.11.0.2 成功复现。

看来是 pandoc 2.10 之后改了语法树，panflute 没跟进。
https://github.com/sergiocorreia/panflute/issues/142

现在唯一的解决方法是退回 pandoc 到 2.9 及之前的版本并等待 panflute 更新。

**Comment by RichardYan314** [comment]
issue 先开着，等 panflute 更新以后再关。

**Comment by Ritsuka314** [comment]
使用 pandoc 2.10 以上版本请更新 panflute 至 2.0.5 以上版本。
